### ISSUE TITLE
FOX-alpha issue in ghidra 10.4+

### ISSUE THREAD

**Issue by uriariel** [0xdea/ghidra-scripts#7]
```
FOX-alpha.java:72: error: '{' expected
public class FOX-alpha extends GhidraScript 
                ^
skipping ghidra_scripts_dea/FOX-alpha.java
```

**Comment by 0xdea** [comment]
Thanks for pointing this out, should be fixed in https://github.com/0xdea/ghidra-scripts/commit/725e62ffc691a27701f316f23f253ccb04172d74.

You should probably also try the more advanced https://github.com/federicodotta/ghidra-scripts/tree/main/FOX that's partially based on my version of FOX.
